# Generated by Django 6.0.3 on 2026-04-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester')], max_length=20)),
                ('result_status', models.BooleanField(blank=True, default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='accounts.batch')),
                ('committee_chairman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_semesters', to='accounts.user')),
            ],
            options={
                'unique_together': {('name', 'batch')},
            },
        ),
    ]
