# Generated by Django 6.0.3 on 2026-04-02 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('credit_hour', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Theory', 'Theory'), ('Thesis', 'Thesis'), ('Project', 'Project')], max_length=20)),
                ('marks_input_status', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.batch')),
                ('course_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to='accounts.user')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.semester')),
            ],
            options={
                'unique_together': {('course_code', 'batch', 'semester')},
            },
        ),
    ]
