# Generated by Django 6.0.3 on 2026-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hour',
            field=models.FloatField(),
        ),
    ]
