# Generated by Django 6.0.3 on 2026-04-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_course_credit_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
