# Generated by Django 6.0.3 on 2026-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_student',
            field=models.CharField(choices=[('Both', 'Both'), ('M.Sc', 'M.Sc'), ('M.Engg', 'M.Engg')], default='Both', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('Both', 'Both'), ('M.Sc', 'M.Sc'), ('M.Engg', 'M.Engg')], default='Both', max_length=10),
        ),
    ]
