# Generated by Django 6.0.3 on 2026-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_course_target_student_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory')], max_length=20),
        ),
    ]
