# Generated by Django 6.0.3 on 2026-04-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_registeredstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
