# Generated by Django 6.0.3 on 2026-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_registeredstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_students',
            field=models.ManyToManyField(blank=True, related_name='additional_enrollment', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory')], default='Theory', max_length=20),
        ),
    ]
