# Generated by Django 6.0.3 on 2026-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_course_additional_students_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hour',
            field=models.FloatField(default=3.0),
        ),
    ]
