# Generated by Django 6.0.3 on 2026-04-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_course_credit_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='additional_students',
        ),
    ]
